junit:
  stage: test
  script:
    - ./gradlew test

generate_artifacts:
  stage: deploy
  script:
    - ./gradlew clean jar
  artifacts:
    paths:
       - build/libs/<seng202_teamX>.jar
