junit:
  stage: test
  script:
    - ./gradlew test

#added checkstyle pipeline tests here
checkstyle_main:
  stage: .pre
  script:
    - ./gradlew checkstyleMain
    - if grep -q '<td>warning</td>' build/reports/checkstyle/main.html; then exit 1; fi
    - if grep -q '<td>error</td>' build/reports/checkstyle/main.html; then exit 1; fi

checkstyle_test:
  stage: .pre
  script:
    - ./gradlew checkstyleTest
    - if grep -q '<td>warning</td>' build/reports/checkstyle/test.html; then exit 1; fi
    - if grep -q '<td>error</td>' build/reports/checkstyle/test.html; then exit 1; fi

generate_artifacts:
  stage: deploy
  script:
    - ./gradlew clean jar
  artifacts:
    paths:
       - build/libs/<seng202_teamX>.jar