junit:
  stage: test
  script:
    - ./gradlew test

#added checkstyle pipeline test here
checkstyle:
  stage: test
  script:
    - ./gradlew checkstyleMain
    - if [ -s build/reports/checkstyle/main.xml ]; then exit 1; fi


generate_artifacts:
  stage: deploy
  script:
    - ./gradlew clean jar
  artifacts:
    paths:
       - build/libs/<seng202_teamX>.jar
