junit:
  stage: test
  script:
    - ./gradlew test

#added checkstyle pipeline test here
checkstyle:
  stage: test
  script:
    - ./gradlew checkstyleMain
    - if grep -q '<td>warning</td>' build/reports/checkstyle/main.html; then exit 1; fi
    - if grep -q '<td>error</td>' build/reports/checkstyle/main.html; then exit 1; fi


generate_artifacts:
  stage: deploy
  script:
    - ./gradlew clean jar
  artifacts:
    paths:
       - build/libs/<seng202_teamX>.jar
